# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3297c1ac9e661c10794a66a894729ce71ce93a4944692caccc17250be1af55c424fa534b2dcc4d32d201b945b1524edc8ec49a4dd6d9eab9ed0057d9dbaa2cc

test:
  secret_key_base: 9b84d8deed5e78d3c6aaa50aef14feb1a8f90cddbd4fe2f5bec11fb35d7f0fe72a78a2b92353520fee762a2c172a2788a7cf8fc312832c4953ad3f347d4db9c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
